'''
添加sqlite持久化存储表
'''
# pylint: disable=invalid-name
# Generated by Django 2.2.10 on 2020-06-21 02:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    '''
    添加rank排名表
    '''

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('rank', models.IntegerField(default=10000000, verbose_name='排名')),
                ('score', models.IntegerField(default=0, verbose_name='分数')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
