exclude: >
    (?x)^(
        .*_pb2(_grpc)?\.py|     # Generated protobuf and grpc files.
    )$
repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint (lint python code)
        entry: python3 -m pylint --rcfile=.pylintrc
        language: system
        types: [python]
      - id: yapf
        name: yapf (format python code)
        entry: python3 -m yapf -i
        language: system
        types: [python]
